export const SET_ITEM = 'SET_ITEM';
export const GET_ITEM = 'GET_ITEM';

export const QUERY_LOCAL_STORE = 'QUERY_LOCAL_STORE';
export const QUERY_SESSION_STORE = 'QUERY_SESSION_STORE';
export const QUERY_COOKIE_STORE = 'QUERY_COOKIE_STORE';

export const QUERY_LOCAL_STORE_SUCCESS = 'QUERY_LOCAL_STORE_SUCCESS';
export const QUERY_SESSION_STORE_SUCCESS = 'QUERY_SESSION_STORE_SUCCESS';
export const QUERY_COOKIE_STORE_SUCCESS = 'QUERY_COOKIE_STORE_SUCCESS';
